name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Install dependencies
      run: |
        cd python
        uv pip install -e ".[dev]"
    - name: Run ruff check
      run: |
        cd python
        uv run ruff check .
    - name: Run ruff format check
      run: |
        cd python
        uv run ruff format --check .
    - name: Run mypy
      run: |
        cd python
        uv run mypy .
  
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        run: |
          cd python
          uv pip install -e ".[test]"
      - name: Run integration tests
        env:
          ROWLAND_API_KEY: ${{ secrets.ROWLAND_API_KEY }}
        run: |
          cd python
          uv run pytest